import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/**
 * Build-time secrets: local.properties (gitignored) for a desk build, the
 * environment for CI. Never committed, and every one of them optional — an
 * absent value builds to an empty string and the feature it feeds stays off.
 */
val localProperties = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }
        ?.inputStream()?.use { load(it) }
}

fun secret(name: String): String =
    localProperties.getProperty(name) ?: System.getenv(name) ?: ""

/** Escaped for the Java string literal buildConfigField writes it into. */
fun buildConfigString(value: String): String =
    "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

/**
 * Bundled TMDB key, so ratings and artwork work out of the box instead of
 * asking every viewer to register for one. Builds fine without it: the key is
 * then empty and enrichment stays opt-in via Settings.
 */
val tmdbApiKey: String = secret("TMDB_API_KEY")

/**
 * The provider's server URL, so onboarding asks for a username and password
 * and not for an address the viewer has no way to know. Empty builds behave
 * exactly as before and ask for all three.
 *
 * Deliberately the host ONLY. It ends up in BuildConfig and therefore inside
 * the APK, where anyone can read it — which is fine for an address (the
 * catalogue manifest already names the same host in plain text) and would not
 * be fine for a credential. Each viewer signs in as themselves.
 */
val providerHost: String = secret("PROVIDER_HOST")

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.agoro.tv"
    compileSdk = 36

    /**
     * Pinned so the build always has the NDK's `strip` on hand. Without it AGP
     * can't strip the prebuilt .so files and merely warns ("Unable to strip the
     * following libraries, packaging them as they are") — which is exactly what
     * CI did through v2.10.2, shipping 8 MB of arm64 debug symbols in
     * libc++_shared.so to every viewer. The workflow installs this same version.
     */
    ndkVersion = "27.1.12297006"

    defaultConfig {
        applicationId = "com.agoro.tv"
        minSdk = 23
        targetSdk = 36
        versionCode = 70
        versionName = "2.25.0"

        buildConfigField("String", "TMDB_API_KEY", buildConfigString(tmdbApiKey))
        buildConfigField("String", "PROVIDER_HOST", buildConfigString(providerHost))

        // One APK for every real device: both ARM ABIs, no x86 (emulators only).
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }
    }

    signingConfigs {
        create("release") {
            val ksPath = System.getenv("DZIDZI_KEYSTORE")
            if (ksPath != null) {
                storeFile = file(ksPath)
                storePassword = System.getenv("DZIDZI_KEYSTORE_PASS")
                keyAlias = System.getenv("DZIDZI_KEY_ALIAS") ?: "dzidzi"
                keyPassword = System.getenv("DZIDZI_KEY_PASS")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = if (System.getenv("DZIDZI_KEYSTORE") != null) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }

    // TV hardware is arm; per-ABI APKs keep downloads small (libVLC is heavy).
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

/**
 * The profile is generated by hand against the TV AVD, not in CI, and the
 * result is committed — so an ordinary release build just packages what is
 * already on disk and needs no device.
 *
 *   ./gradlew :app:generateBaselineProfile
 */
baselineProfile {
    // Committed rather than regenerated per build: generation needs a running
    // device, which release CI does not have.
    saveInSrc = true
    automaticGenerationDuringBuild = false
    // R8 rewrites method signatures, so the profile has to be rewritten with
    // it or half the rules stop matching in the shipped APK.
    dexLayoutOptimization = true
}

dependencies {
    baselineProfile(project(":baselineprofile"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.splashscreen)
    implementation(libs.androidx.profileinstaller)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.icons)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.tv.material)

    // Every container an IPTV provider might hand us: progressive TS/MP4/MKV
    // from the core, plus HLS, DASH, SmoothStreaming, RTSP and RTMP.
    implementation(libs.media3.exoplayer)
    implementation(libs.media3.exoplayer.hls)
    implementation(libs.media3.exoplayer.dash)
    implementation(libs.media3.exoplayer.smoothstreaming)
    implementation(libs.media3.exoplayer.rtsp)
    implementation(libs.media3.datasource.rtmp)
    implementation(libs.media3.ui)
    // FFmpeg audio decoder, built from the androidx/media 1.8.0 source tree —
    // Google does not publish it to Maven. It is what gives AC-3, E-AC-3, DTS
    // and TrueHD audio on devices whose hardware decoders don't cover them,
    // which on IPTV is the difference between a channel with sound and one
    // without. DefaultRenderersFactory finds it reflectively, so nothing has
    // to reference it in code. See docs/ffmpeg-decoder.md to rebuild.
    implementation(files("libs/media3-decoder-ffmpeg-1.8.0.aar"))
    implementation(libs.media3.session)
    // MediaSessionCompat for the VLC engine's minimal session.
    implementation(libs.androidx.media)
    implementation(libs.libvlc)

    implementation(libs.coil.compose)
    implementation(libs.coil.network.okhttp)
    implementation(libs.okhttp)
    implementation(libs.zxing.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation("net.sf.kxml:kxml2:2.3.0")
}
