import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/**
 * Generates the baseline profile shipped in the release APK.
 *
 * The app already depended on androidx.profileinstaller, but nothing ever
 * produced a profile for it to install — so on every cold start ART was
 * interpreting Compose and the whole channel-list path from scratch, which is
 * exactly where a low-end TV box has the least headroom.
 *
 * Run: ./gradlew :app:generateBaselineProfile   (with a device/emulator attached)
 */
plugins {
    alias(libs.plugins.android.test)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.nuxcor.nuxtv.baselineprofile"
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // Profile generation needs 28+; the app itself still ships to 23,
        // which simply gets no profile.
        minSdk = 28
        targetSdk = 36
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ":app"
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

baselineProfile {
    // One device, one run: this is generated by hand against the TV AVD, not
    // in CI, so there is nothing to manage a device pool for.
    useConnectedDevices = true
}

dependencies {
    implementation(libs.androidx.test.junit)
    implementation(libs.androidx.uiautomator)
    implementation(libs.androidx.benchmark.macro.junit4)
}
